-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 23:46:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brocante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brocante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brocante` DEFAULT CHARACTER SET utf8 ;
USE `brocante` ;

-- -----------------------------------------------------
-- Table `brocante`.`emplacements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brocante`.`emplacements` ;

CREATE TABLE IF NOT EXISTS `brocante`.`emplacements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `taille` VARCHAR(45) NOT NULL,
  `prix` INT NOT NULL,
  `paye` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brocante`.`administrateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brocante`.`administrateurs` ;

CREATE TABLE IF NOT EXISTS `brocante`.`administrateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ok` TINYINT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brocante`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brocante`.`clients` ;

CREATE TABLE IF NOT EXISTS `brocante`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `codepostal` INT NULL,
  `ville` VARCHAR(45) NULL,
  `emplacements_id` INT NOT NULL,
  `administrateurs_id` INT NOT NULL,
  PRIMARY KEY (`id`, `emplacements_id`, `administrateurs_id`),
  INDEX `fk_clients_emplacements1_idx` (`emplacements_id` ASC),
  INDEX `fk_clients_administrateurs1_idx` (`administrateurs_id` ASC),
  CONSTRAINT `fk_clients_emplacements1`
    FOREIGN KEY (`emplacements_id`)
    REFERENCES `brocante`.`emplacements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_administrateurs1`
    FOREIGN KEY (`administrateurs_id`)
    REFERENCES `brocante`.`administrateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
